version: "3.9"

services:
  blackjackserver:
    build: blackjackserver/
    container_name: blackjackserver
    ports:
      - "8080:8080"
    volumes:
      - ./blackjackserver/results:/root/app/results
      # - ./blackjackserver/logs:/root/app/logs
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  apiserver:
    build: apiserver/
    container_name: apiserver
    ports:
      - "3333:3333"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - apiserver
      - blackjackserver
      - redis

  # client:
  #   image: 127.0.0.1:5000/client
  #   build: client/
  #   container_name: blackjack_client
  #   links:
  #     - "app:app"
  #   depends_on:
  #     - app
  #   environment:
  #     - BJ_HOST=app
