version: "3.9"

services:
  blackjack:
    # image: 127.0.0.1:5000/blackjack
    build: .
    container_name: blackjack
    ports:
      - "8080:8080"
    # deploy:
    #   mode: replicated
    #   replicas: 2
    # TODO add volume

  apiserver:
    # image: 127.0.0.1:5000/blackjack
    build: apiserver/
    container_name: apiserver
    ports:
      - "3333:3333"
      
  redis:
    image: redis:latest
    container_name: redis-instance
    ports:
      - "6379:6379"
    # deploy:
    #   mode: replicated
    #   replicas: 2
    # TODO add volume

  # client:
  #   image: 127.0.0.1:5000/client
  #   build: client/
  #   container_name: blackjack_client
  #   links:
  #     - "app:app"
  #   depends_on:
  #     - app
  #   environment:
  #     - BJ_HOST=app